In [1]:
import numpy as np 
import pandas as pd 

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/imdb-dataset-of-50k-movie-reviews/IMDB Dataset.csv


In [2]:
df=pd.read_csv('/kaggle/input/imdb-dataset-of-50k-movie-reviews/IMDB Dataset.csv')

In [24]:
pd.set_option('display.max_colwidth', 100)
df.review

0        one of the other reviewers has mentioned that after watching just  oz episode youll be hooked th...
1        a wonderful little production br br the filming technique is very unassuming very oldtimebbc fas...
2        i thought this was a wonderful way to spend time on a too hot summer weekend sitting in the air ...
3        basically theres a family where a little boy jake thinks theres a zombie in his closet  his pare...
4        petter matteis love in the time of money is a visually stunning film to watch mr mattei offers u...
                                                        ...                                                 
49995    i thought this movie did a down right good job it wasnt as creative or original as the first but...
49996    bad plot bad dialogue bad acting idiotic directing the annoying porn groove soundtrack that ran ...
49997    i am a catholic taught in parochial elementary schools by nuns taught by jesuit priests in high ...
49998    im going t

In [4]:
df

review  \
0      One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked....   
1      A wonderful little production. <br /><br />The filming technique is very unassuming- very old-ti...   
2      I thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air...   
3      Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his...   
4      Petter Mattei's "Love in the Time of Money" is a visually stunning film to watch. Mr. Mattei off...   
...                                                                                                    ...   
49995  I thought this movie did a down right good job. It wasn't as creative or original as the first, ...   
49996  Bad plot, bad dialogue, bad acting, idiotic directing, the annoying porn groove soundtrack that ...   
49997  I am a Catholic taught in parochial elementary schools by nuns, taught by Jesuit priests in high...   
49998  I'm going to have to disagree with the previous comment and side with Maltin on this one. This i...   
49999  No one expects the Star Trek movies to be high art, but the fans do expect a movie that is as go...   

      sentiment  
0      positive  
1      positive  
2      positive  
3      negative  
4      positive  
...         ...  
49995  positive  
49996  negative  
49997  negative  
49998  negative  
49999  negative  

[50000 rows x 2 columns]

In [5]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [6]:
df['sentiment'].value_counts()

positive    25000
negative    25000
Name: sentiment, dtype: int64

In [7]:
import nltk
from nltk.stem import PorterStemmer
from nltk.tokenize import sent_tokenize, word_tokenize
import re
import string

In [8]:
def preprocess_data(text):
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('\[.*?\]', '', text)
    text = text.lower()
    text = re.sub('\w*\d\w*', '', text)
    text = re.sub("\\W"," ",text) 
    text = re.sub('\n', '', text)
  
    
    return text

In [9]:
df['review']=df['review'].apply(preprocess_data)

In [25]:
df

review  \
0      one of the other reviewers has mentioned that after watching just  oz episode youll be hooked th...   
1      a wonderful little production br br the filming technique is very unassuming very oldtimebbc fas...   
2      i thought this was a wonderful way to spend time on a too hot summer weekend sitting in the air ...   
3      basically theres a family where a little boy jake thinks theres a zombie in his closet  his pare...   
4      petter matteis love in the time of money is a visually stunning film to watch mr mattei offers u...   
...                                                                                                    ...   
49995  i thought this movie did a down right good job it wasnt as creative or original as the first but...   
49996  bad plot bad dialogue bad acting idiotic directing the annoying porn groove soundtrack that ran ...   
49997  i am a catholic taught in parochial elementary schools by nuns taught by jesuit priests in high ...   
49998  im going to have to disagree with the previous comment and side with maltin on this one this is ...   
49999  no one expects the star trek movies to be high art but the fans do expect a movie that is as goo...   

       sentiment  
0              1  
1              1  
2              1  
3              0  
4              1  
...          ...  
49995          1  
49996          0  
49997          0  
49998          0  
49999          0  

[50000 rows x 2 columns]

In [11]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [12]:
df['sentiment']=le.fit_transform(df['sentiment'])

In [13]:
df

review  \
0      one of the other reviewers has mentioned that after watching just  oz episode youll be hooked th...   
1      a wonderful little production br br the filming technique is very unassuming very oldtimebbc fas...   
2      i thought this was a wonderful way to spend time on a too hot summer weekend sitting in the air ...   
3      basically theres a family where a little boy jake thinks theres a zombie in his closet  his pare...   
4      petter matteis love in the time of money is a visually stunning film to watch mr mattei offers u...   
...                                                                                                    ...   
49995  i thought this movie did a down right good job it wasnt as creative or original as the first but...   
49996  bad plot bad dialogue bad acting idiotic directing the annoying porn groove soundtrack that ran ...   
49997  i am a catholic taught in parochial elementary schools by nuns taught by jesuit priests in high ...   
49998  im going to have to disagree with the previous comment and side with maltin on this one this is ...   
49999  no one expects the star trek movies to be high art but the fans do expect a movie that is as goo...   

       sentiment  
0              1  
1              1  
2              1  
3              0  
4              1  
...          ...  
49995          1  
49996          0  
49997          0  
49998          0  
49999          0  

[50000 rows x 2 columns]

In [26]:
firstcol=df['review']
secondcol=df['sentiment']

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
firstcol_train,firstcol_test,secondcol_train,secondcol_test=train_test_split(firstcol,secondcol,random_state=0,test_size=0.2)

In [17]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(1,2))

In [27]:
firstcol_train_trans=cv.fit_transform(firstcol_train)

In [19]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()

In [28]:
lr.fit(firstcol_train_trans,secondcol_train)
pred_secondcol=lr.predict(cv.transform(firstcol_test))

/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [29]:
pred_secondcol

array([1, 0, 1, ..., 1, 0, 0])

In [ ]:
firstcol_test

In [30]:
from sklearn.metrics import accuracy_score
score_1=accuracy_score(secondcol_test,pred_secondcol)

In [31]:
score_1


0.9017

In [39]:
text =["easy to give high rating"]
p=lr.predict(cv.transform(text))

In [40]:
p

array([0])

In [41]:
text =["hard to give high rating"]
p=lr.predict(cv.transform(text))

In [42]:
p

array([0])